name 'metasploitable'
maintainer 'Rapid7'
maintainer_email ''
license 'BSD-3-clause'
description 'Installs/Configures metasploitable3'
long_description 'Installs/Configures metasploitable3'
version '0.1.0'

issues_url 'https://github.com/rapid7/metasploitable/issues'
source_url 'https://github.com/rapid7/metasploitable'
