#!/bin/sh
### BEGIN INIT INFO
# Provides:          readme_app
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Init script for readme_app
# Description:       Start/stop readme_app
### END INIT INFO

DESC="readme_app"
NAME=readme_app
#DAEMON=

do_start()
{
   echo "Starting readme_app.";
   cd /opt/readme_app
   rails s &
}

do_stop()
{
   echo "Stopping readme_app."
   killall ruby
}


case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
esac

exit 0