#!/bin/sh
### BEGIN INIT INFO
# Provides:          unrealircd
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Init script for unrealircd
# Description:       Start/stop unrealircd
### END INIT INFO

DESC="unrealircd"
NAME=unrealircd
#DAEMON=

do_start()
{
   /opt/unrealircd/Unreal3.2/unreal start
}

do_stop()
{
   /opt/unrealircd/Unreal3.2/unreal stop
}


case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
esac

exit 0