#!/bin/sh
### BEGIN INIT INFO
# Provides:          proftpd
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Init script for proftpd
# Description:       Start/stop proftpd
### END INIT INFO

DESC="proftpd"
NAME=proftpd
#DAEMON=

do_start()
{
   echo "Starting proftpd.";
   /opt/proftpd/sbin/proftpd
}

do_stop()
{
   echo "Stopping proftpd."
   killall proftpd
}


case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
esac

exit 0