#!/bin/sh
### BEGIN INIT INFO
# Provides:          proftpd
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Init script for proftpd
# Description:       Start/stop proftpd
### END INIT INFO

DESC="proftpd"
NAME=proftpd
#DAEMON=

do_start()
{
   echo "Starting proftpd.";
   /opt/proftpd/sbin/proftpd
}

do_stop()
{
   echo "Stopping proftpd."
   killall proftpd
}

do_status()
{
   if pgrep -f ^proftpd > /dev/null ; then
      echo 'Running';
      exit 0;
   else
      echo 'Not running';
      exit 1;
   fi

}



case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
   status)
     do_status
     ;;
esac

exit 0
